baseurl = "https://www.haiku-os.org/"
title = "Haiku Project"
copyright = "2001-2017 Haiku Inc."
languageCode = "en-us"
canonifyurls = true
rssURI = "rss.xml"
[params]
  AuthorName = "Haiku Project"
  discourseUrl = "https://discuss.haiku-os.org/"
